#!/usr/bin/env python3
"""Crop textbook figures that replace low-quality question pictures (owner's request, 2026-09-25).

Where the textbook prints the same drawing or sign that a question shows as a small or blurry copy
cut from a sample exam, the book's version is used instead. Each crop box was chosen and checked
visually (no OCR) in pixels of the book page rendered 3000 px tall by scripts/render_pdf_pages.swift.

Input:  data/book-figure-crops.json   figures: file, bookPage, box, and the questions using the figure
                                       (with the picture each question showed before).
Output: assets/questions/<file>        the crops (white margins trimmed, at most 900 px, 128 colours)
        data/book-figures.js           per question: new file, previous picture, book page; folded into
                                       the documented corrections by data/question-corrections.js

usage: crop_book_figures.py   (renders the needed pages from pdf's/main book.pdf into tmp/book-renders/)
"""
import json
import subprocess
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[2]
BOOK = ROOT / "pdf's" / "main book.pdf"
RENDERS = ROOT / "tmp" / "book-renders"
ASSETS = ROOT / "assets" / "questions"
RENDER_HEIGHT = 3000
MAX_SIDE = 900
MARGIN = 14
WHITE = 232  # grey level above which a pixel counts as page background when trimming


def render(book_page):
    pdf_page = book_page + 2  # printed page = PDF page - 2
    path = RENDERS / f"page-{pdf_page:03d}.png"
    if not path.exists():
        RENDERS.mkdir(parents=True, exist_ok=True)
        subprocess.run(["swift", str(ROOT / "scripts" / "render_pdf_pages.swift"), str(BOOK), str(pdf_page), str(pdf_page),
                        str(RENDERS), str(RENDER_HEIGHT)], check=True)
    return Image.open(path).convert("RGB")


def trim(image):
    """Tighten the crop to its ink, keeping a small white margin; never grows past the chosen box."""
    ink = ImageOps.invert(image.convert("L")).point(lambda value: 255 if value > 255 - WHITE else 0)
    box = ink.getbbox()
    if not box:
        return image
    x0, y0, x1, y1 = box
    return image.crop((max(0, x0 - MARGIN), max(0, y0 - MARGIN), min(image.width, x1 + MARGIN), min(image.height, y1 + MARGIN)))


def main():
    spec = json.loads((ROOT / "data" / "book-figure-crops.json").read_text(encoding="utf-8"))
    assert spec["renderHeight"] == RENDER_HEIGHT
    wanted = {figure["file"] for figure in spec["figures"]}
    for stale in ASSETS.glob("q-book-*.png"):
        if stale.name not in wanted:
            stale.unlink()
    pages = {}
    by_question = {}
    for figure in spec["figures"]:
        page = pages.setdefault(figure["bookPage"], render(figure["bookPage"]))
        crop = trim(page.crop(tuple(figure["box"])))
        if max(crop.size) > MAX_SIDE:
            crop.thumbnail((MAX_SIDE, MAX_SIDE), Image.LANCZOS)
        crop.quantize(colors=128, method=Image.Quantize.MEDIANCUT).save(ASSETS / figure["file"], optimize=True)
        for question in figure["questions"]:
            by_question[question["id"]] = {"file": figure["file"], "bookPage": figure["bookPage"], "previousImage": question["previousImage"]}
    lines = [
        "// Generated by scripts/assets/crop_book_figures.py from data/book-figure-crops.json; do not edit by hand.",
        "// Questions whose small or blurry exam picture is replaced by the same figure cropped from the textbook.",
        "export const bookFigureImages = {",
    ]
    lines += [f"  {json.dumps(qid)}: {json.dumps(entry, ensure_ascii=False)}," for qid, entry in sorted(by_question.items())]
    lines.append("};")
    (ROOT / "data" / "book-figures.js").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(spec['figures'])} figures, {len(by_question)} questions")


if __name__ == "__main__":
    main()
